#include "./1-numbers-tasks/1-numbers-tasks.cpp"
#include "./2-booleans-tasks/2-booleans-tasks.cpp"
#include "./3-conditions-tasks/3-conditions-tasks.cpp"
#include "./4-loops-tasks/4-loops-tasks.cpp"
#include "./5-conditions-n-loops-tasks/5-conditions-n-loops-tasks.cpp"
